; Enemy Definitions
INCLUDE_DINO = 0

; Levels
INCLUDE_TEST_LEVELS = 0
INCLUDE_DEMO_LEVELS = 0

; Properties
IS_EXPANDED_ROM = 0 || INCLUDE_DINO
NUMBER_OF_PRG_BANKS = 16 + (16 * IS_EXPANDED_ROM)
NUMBER_OF_CHR_BANKS = 16 + (16 * IS_EXPANDED_ROM)
UNUSED_EXTENDED_CHR_BANKS = 128 - (INCLUDE_DINO != 0)
KEEP_USED_LEVELS = !(INCLUDE_TEST_LEVELS || INCLUDE_DEMO_LEVELS)
